src/uptime-card.ts
=> Fix undefined API response from hass error

src/style.ts
=> Make card less theme dependent

src/editor.ts
=> Remove binary sensor filter in editor

src/uptime-card.ts
=> Fetch data from HA API immediately after creation

README.md, src/const.ts, src/uptime-card.ts
=> Fix blink card bug

src/editor.ts
=> Fix editor resetting severity and boolean

README.md, src/const.ts, src/editor.ts, src/style.ts, src/types/card.ts, src/types/config.ts, src/uptime-card.ts, src/utils.ts
=> Add tooltip

README.md, src/const.ts, src/editor.ts, src/types/config.ts, src/uptime-card.ts, src/utils.ts, tsconfig.json
=> Add template based status

README.md, src/const.ts, src/editor.ts, src/types/config.ts, src/types/editor.ts, src/uptime-card.ts
=> Make card clickable

README.md, src/const.ts, src/editor.ts, src/style.ts, src/types/config.ts, src/uptime-card.ts
=> Add alignment

src/style.ts, src/uptime-card.ts
=> Limit click to information only

src/uptime-card.ts, src/utils.ts
#46 
I decided to use javascript to clip the text and not CSS because I plan to use grid instead of flexbox in the future, so I will implement the correct clipping method when the change will be effective.
=> Add clipping for title and status

README.md, src/editor.ts, src/types/config.ts, src/uptime-card.ts
=> Add new click possibilities

src/uptime-card.ts
=> Add cursor pointer for any tap action

README.md, src/types/card.ts, src/types/config.ts, src/uptime-card.ts
=> Add color thresholds

README.md, src/style.ts, src/uptime-card.ts
=> Modify icon rendering to support image

README.md, src/editor.ts, src/types/card.ts, src/types/config.ts, src/uptime-card.ts
=> Add the possibility to monitor an attribute instead of the state

src/uptime-card.ts
=> Fix color thresholds

README.md, src/uptime-card.ts
=> Handle minutes for hours_to_show footer text

README.md, src/uptime-card.ts, src/utils.ts
=> Add configuration to templating

src/style.ts, src/uptime-card.ts
using left/right header alignment doesn't work (the example images in the README can't be created). This PR fixes that.
The build passes and it works on my HA instance.
@dylandoamaral can you please CR?
=> fix alignment issues

README.md, src/const.ts, src/editor.ts
=> fix: default icon color

src/uptime-card.ts
=> fix: time format for 24-hour clock

src/uptime-card.ts
=> fix: bar position

.devcontainer/ui-lovelace.yaml, src/uptime-card.ts
=> feat: support switch entity

README.md, src/editor.ts, src/types/config.ts, src/uptime-card.ts
This is some initial PR for #145 .
If it's fine from card logic and I didn't miss anything, I can proceed with adding relevant docs.
=> feat(state): add none state mapping

src/uptime-card.ts
=> fix: average text when 0 uptime

.devcontainer/ui-lovelace.yaml, src/const.ts, src/editor.ts, src/style.ts, src/types/config.ts, src/uptime-card.ts
=> feat: add color footer configuration

README.md, src/editor.ts, src/types/config.ts, src/uptime-card.ts
=> feat: add color ko_icon configuration

.devcontainer/ui-lovelace.yaml, README.md, src/const.ts, src/editor.ts, src/types/config.ts, src/uptime-card.ts
=> feat: add duration configuration and remove hours_to_show

README.md
=> chore: fix readme duration unit default value
